name: CD pipeline

on:
  push:
    branches: [ "main-test" ]
  pull_request:
    branches: [ "main-test" ]

permissions: write-all

jobs:
           
  push-test-to-prod-repo:
   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'Product-Development-CodeCrusaders/Prod-FlashLearn'
        ref: main-prod
        token: ${{ secrets.CLA_WRITE_ACCESS }}

    - name: Add test repo and pull to prod repo
      run: |
        
        git remote add test https://github.com/Product-Development-CodeCrusaders/Test-FlashLearn
        git remote -v
        git branch -a
        git config user.name Niharika-R5
        git config user.email eng21ct0028@dsu.edu.in
        
        git pull test main-test
        #We use pull here to pull to the local system but when we need to push it to the remote repo ,we use push
        #hence pull and push is used here
        git push 
      