name: Basic deploy
on:
  push:
    branches: [ main-prod ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment: 
     name: ${{ github.ref_name }}
     url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.0
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          app_port: 3000

          aws_ec2_instance_type: t3.micro
          bitops_code_store: true
          tf_stack_destroy: false 
          tf_state_bucket_destroy: false
          ansible_skip: false
          aws_vpc_create: true

